name: Build Release APK

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Write local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Restore Gradle cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle/libs.versions.toml') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Restore Android SDK cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.android
            $ANDROID_SDK_ROOT
          key: android-sdk-${{ runner.os }}-sdk36
          restore-keys: |
            android-sdk-${{ runner.os }}-

      - name: Restore keystore
        run: |
          echo "${{ secrets.TIMECALC_KEYSTORE_B64 }}" | base64 -d > timecalc-release.jks

      - name: Build release
        env:
          TIMECALC_KEYSTORE_PASSWORD: ${{ secrets.TIMECALC_KEYSTORE_PASSWORD }}
          TIMECALC_KEY_PASSWORD: ${{ secrets.TIMECALC_KEY_PASSWORD }}
          TIMECALC_KEY_ALIAS: ${{ secrets.TIMECALC_KEY_ALIAS }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Save Gradle cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle/libs.versions.toml') }}

      - name: Save Android SDK cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.android
            $ANDROID_SDK_ROOT
          key: android-sdk-${{ runner.os }}-sdk36

      - name: Rename APK
        run: |
          VERSION="${{ gitea.ref_name }}"
          if [ -z "$VERSION" ]; then
            VERSION="dev"
          fi
          cp app/build/outputs/apk/release/app-release.apk "TimeCalc_${VERSION}.apk"

      - name: Create release & upload asset
        env:
          GITEA_TOKEN: ${{ secrets.RELEASE_GITEA_TOKEN }}
          GITEA_URL: http://gitea:3000
          REPO_OWNER: domgregori
          REPO_NAME: timecalc
          TAG: ${{ gitea.ref_name }}
        run: |
          APK="TimeCalc_${TAG}.apk"

          # Create release (ignore error if it already exists)
          CREATE_RESPONSE=$(curl -sS -X POST \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/json" \
            "${GITEA_URL}/api/v1/repos/${REPO_OWNER}/${REPO_NAME}/releases" \
            -d "{\"tag_name\":\"${TAG}\",\"name\":\"${TAG}\",\"draft\":false,\"prerelease\":false}" \
            || true)

          # Get release id (from create response or existing tag)
          RELEASE_ID=$(echo "$CREATE_RESPONSE" | sed -n 's/.*"id":[ ]*\\([0-9]*\\).*/\\1/p')
          if [ -z "$RELEASE_ID" ]; then
            RELEASE_ID=$(curl -sS \
              -H "Authorization: token ${GITEA_TOKEN}" \
              "${GITEA_URL}/api/v1/repos/${REPO_OWNER}/${REPO_NAME}/releases/tags/${TAG}" \
              | sed -n 's/.*"id":[ ]*\\([0-9]*\\).*/\\1/p')
          fi

          if [ -z "$RELEASE_ID" ]; then
            echo "Failed to determine release id for tag ${TAG}"
            exit 1
          fi

          # Upload asset
          curl -sS -X POST \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"${APK}" \
            "${GITEA_URL}/api/v1/repos/${REPO_OWNER}/${REPO_NAME}/releases/${RELEASE_ID}/assets?name=${APK}"

#
